# Generated by Django 6.0.3 on 2026-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('education', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate')], max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('work_preference', models.CharField(choices=[('remote', 'Remote'), ('home', 'Home Based'), ('office', 'Office')], max_length=50)),
                ('career_gap_years', models.IntegerField(default=0)),
                ('interests', models.ManyToManyField(blank=True, to='recommendation.interest')),
                ('skills', models.ManyToManyField(blank=True, to='recommendation.skill')),
            ],
        ),
    ]
